export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const SEND_CONTACT_FORM_SUCCESS = "SEND_CONTACT_FORM_SUCCESS";
export const RESET_CONTACT_FORM = "RESET_CONTACT_FORM";
export const SET_CANDIDATE_ATTRIBUTES = "SET_CANDIDATE_ATTRIBUTES";
export const SUCCESS_CANDIDATE_REGISTRATION = "SUCCESS_CANDIDATE_REGISTRATION";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const CREATE_PORTFOLIO = "CREATE_PORTFOLIO";
export const LOAD_PORTFOLIOS_SUCCESS = "LOAD_PORTFOLIOS_SUCCESS";
export const LOAD_PORTFOLIOS_FAILURE = "LOAD_PORTFOLIOS_FAILURE";

export const LOAD_PORTFOLIO_SUCCESS = "LOAD_PORTFOLIO_SUCCESS";
export const LOAD_PORTFOLIO_FAILURE = "LOAD_PORTFOLIO_FAILURE";

export const LOAD_PORTFOLIO_HOLDING_SUCCESS = "LOAD_PORTFOLIO_HOLDING_SUCCESS";
export const LOAD_PORTFOLIO_HOLDING_FAILURE = "LOAD_PORTFOLIO_HOLDING_FAILURE";
export const CREATE_PORTFOLIO_SUCCESS = "CREATE_PORTFOLIO_SUCCESS";

export const UPDATE_PORTFOLIO_SUCCESS = "UPDATE_PORTFOLIO_SUCCESS";

export const DELETE_PORTFOLIO_SUCCESS = "DELETE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_OPTIMISTIC = "DELETE_PORTFOLIO_OPTIMISTIC";

export const LOAD_TRANSACTIONS_SUCCESS = "LOAD_TRANSACTIONS_SUCCESS";
export const LOAD_TRANSACTIONS_FAILURE = "LOAD_TRANSACTIONS_FAILURE";

export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
